### ISSUE TITLE
[SDK-Version] Issue Title Failed to load module 'CometChatPro'

### ISSUE THREAD

**Issue by AnkitGabani** [cometchat-pro/ios-swift-chat-app#14]
used  pod 'CometChatPro', '2.1.0'

When import CometChatPro in AppDelegate.swift, I got Error that...
![Screenshot 2020-08-21 at 7 45 30 PM](https://user-images.githubusercontent.com/31876788/90900325-e4dea080-e3e6-11ea-8ace-b049a70ed394.png)

![Screenshot 2020-08-21 at 7 25 36 PM](https://user-images.githubusercontent.com/31876788/90900119-903b2580-e3e6-11ea-92c6-e529e8fb51e3.png)

**Comment by pushpsenairekar2911** [comment]
Hello @AnkitGabani, 

Please, clean derived data and reinstall pods. This will resolve your issue.

**Comment by pushpsenairekar2911** [comment]
Hello @AnkitGabani, 

I hope your issue has been resolved. Please reopen this if you're still facing an issue.
