### ISSUE TITLE
pod not working

### ISSUE THREAD

**Issue by mm2u** [cometchat-pro/ios-swift-chat-app#15]
I download the sample app and try to pod install or pod install --repo-update
but it is not working.

its stuck on Installing CometChatPro (2.1.2), no response at all
someone can help me?

my Xcode is 12.0.1

**Comment by lmcmz** [comment]
Same here, the error is:

```
Unable to load contents of file list: '/Users/lmcmz/Downloads/ios-swift-chat-app-master/CometChatSwift/Pods/Target Support Files/Pods-CometChatSwift/Pods-CometChatSwift-artifacts-Debug-input-files.xcfilelist'
```

**Comment by pushpsenairekar2911** [comment]
Hello @mm2u ,

I hope you'll be able to install our SDK till now. Closing this issue, if you're still facing the same issue then you can reopen it again.

Thanks.
