### ISSUE TITLE
Demo Will not build

### ISSUE THREAD

**Issue by hsmith825** [cometchat-pro/ios-swift-chat-app#16]
I am on Xcode 12.1. I downloaded the zip file, loaded the dependencies with pod install. Loaded CometChat Swft.  Added the following:   appId, apiKey,   region.  I get the following build error:  
Unable to load contents of file list: '/Target Support Files/Pods-CometChatSwift/Pods-CometChatSwift-artifacts-Debug-input-files.xcfilelist'

Any help is appreciated.
Thanks!
hsmith825

**Comment by pushpsenairekar2911** [comment]
Hello @hsmith825, 

I hope you'll be able to build the new UI Kit project. Closing this issue, if you're still facing the same issue then please let us know.
