### ISSUE TITLE
No such module 'CometChatPro'

### ISSUE THREAD

**Issue by Astha725** [cometchat-pro/ios-swift-chat-app#17]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what you exactly is happening.

**Screenshots** (optional)

**Enviorment/Platfrom (please complete the following information):**
 - iOS Version[ e.g iOS 12.1 ]
 - CometChat SDK Version[ e.g. 1.8.4]

**Files (Optional)**
 - `podfile` 

**Logs (Error Logs)**
- Error Log
- Debug Log

**Additional context**

**Comment by pushpsenairekar2911** [comment]
Hello @Astha725,

Please perform the below steps to resolve the issue.

1. pod deintegrate
2. sudo gem install cocoapods-clean
3. pod clean
4. Open the project and delete the "Pods" folder that should be red.
5. pod setup
6. pod install

Closing this issue, you can reopen this if you're still facing the issue.

**Comment by shakyevan444** [comment]
i have the sam issue and that didnt help

**Comment by zhihuij** [comment]
This info may help: ensure you're opening the .xcworkspace file, not the .xcodeproj file.
