### ISSUE TITLE
2.6.1 can't update the pods 

### ISSUE THREAD

**Issue by dipesh-lumintechsys** [cometchat-pro/ios-swift-chat-app#18]
![Screenshot 2021-01-06 at 9 38 37 PM](https://user-images.githubusercontent.com/76449109/103790884-c4e30d00-5067-11eb-9aa5-13c8f446b177.png)

Xcode version:- 12.3 
Cocoa Pods:- 1.10.0

**Comment by pushpsenairekar2911** [comment]
Hello @dipesh-lumintechsys, 

Please perform the below steps to resolve the issue.

1. pod deintegrate
2. sudo gem install cocoapods-clean
3. pod clean
4. Open the project and delete the "Pods" folder that should be red.
5. pod setup
6. pod install

Closing this issue, you can reopen this if you're still facing the issue.
