### ISSUE TITLE
[SDK-Version] Issue Title '2.1.4'

### ISSUE THREAD

**Issue by rizwan143** [cometchat-pro/ios-swift-chat-app#19]
pod is not updating from version '2.1.4' to '2.1.5' . It seems like you didn't upload latest version. It shows me error 
[!] CocoaPods could not find compatible versions for pod "CometChatPro":
  In Podfile:
    CometChatPro (= 2.1.5)

None of your spec sources contain a spec satisfying the dependency: `CometChatPro (= 2.1.5)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
![Screenshot 2021-01-14 at 1 35 33 PM](https://user-images.githubusercontent.com/42130988/104564964-62909a80-566d-11eb-848e-32938a7253a0.png)

**Comment by pushpsenairekar2911** [comment]
Hello @rizwan143, 

Please perform the below steps to resolve the issue. 

**1. pod deintegrate
2. sudo gem install cocoapods-clean
3. pod clean
4. Open the project and delete the "Pods" folder that should be red.
5. pod setup
6. pod install**

Closing this issue, you can reopen this if you're still facing the issue.
