### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by frontier17** [cometchat-pro/ios-swift-chat-app#21]
Hello,

I got this error on build, what should I do?

'TypingIndicator' has different definitions in different modules; first difference is definition in module 'CometChatPro.Swift' found super class with type 'NSObject'

Note: 
All steps were done in quick start.
pod version: 'CometChatPro', '2.1.5'

<img width="1792" alt="Screen Shot 2021-02-17 at 16 11 48" src="https://user-images.githubusercontent.com/525921/108210046-1ccb6400-713c-11eb-9466-23b3c663a1cb.png">

**Comment by jeetkapadia** [comment]
Hi @frontier17,

We have tested this issue in our iOS Swift Sample App and in our Objective C Sample App and we are unable to encounter the same. We have tested it in Xcode 12.2. Also please try clearing the derived data and then building the project. In case if the issue persists then please let us know whether you are using swift or objective C in your project along with the Xcode version used by you. 

Regards,
Jeet Kapadia

**Comment by frontier17** [comment]
I tried but still it didn't work. 

Xcode: Version 12.3
Lang: Swift 5

**Comment by 01234abhishek** [comment]
![Screenshot 2021-03-30 at 6 37 10 PM](https://user-images.githubusercontent.com/73534855/112993539-f19a5280-9186-11eb-8db2-94acee0d4db1.png)
Hi I have download the project and then deintegrate and clean the project. delete the derived file. but still it is showing this error. Can you guys help me regarding this. I found this project very fine.
I am using Xcode 12.4
Swift 5. 
Thanks
